language: php
php:
  - '5.6'
  - '7.1'
  - '7.3'

install:
  - composer self-update # This should not be required, but it is always a good practice to update composer
  - composer install

branches:
  only:
    - master