language: php
php:
  - '5.6'
  - '7.1'
  - '7.3'

before_script:
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep "Fatal error"; then exit 1; fi

install:
  - composer self-update
  - composer install

script: exit 0

branches:
  only:
    - master